/**
 * 게임 영문 슬러그 → 한국 서비스명.
 *
 * 한국에 정식 서비스 중이거나 한글명이 실제로 검색되는 게임만 넣는다.
 * 여기 없는 게임은 영문명 그대로 노출한다 — 억지 번역은 검색에도 안 걸리고 신뢰만 깎는다.
 */
export const KO_NAMES = {
  'aether-gazer': '에테르 게이저',
  'afk-arena': 'AFK 아레나',
  'afk-journey': 'AFK 저니',
  'arknights': '명일방주',
  'azur-lane': '벽람항로',
  'black-clover-m': '블랙클로버 모바일',
  'blade-soul-heroes': '블레이드 앤 소울 히어로즈',
  'blue-archive': '블루 아카이브',
  'boom-beach': '붐비치',
  'brawl-stars': '브롤스타즈',
  'call-of-duty-mobile': '콜 오브 듀티 모바일',
  'clash-of-clans': '클래시 오브 클랜',
  'clash-royale': '클래시 로얄',
  'coin-master': '코인마스터',
  'cookie-run-kingdom': '쿠키런: 킹덤',
  'cookie-run-tower-of-adventures': '쿠키런: 모험의 탑',
  'cookierun-ovensmash': '쿠키런: 오븐스매시',
  'counter-side': '카운터사이드',
  'diablo-immortal': '디아블로 이모탈',
  'dislyte': '디스라이트',
  'duck-survival': '덕 서바이벌',
  'epic-seven': '에픽세븐',
  'era-of-conquest': '정복의 시대',
  'eversoul': '에버소울',
  'evony-the-kings-return': '에보니',
  'free-fire': '프리파이어',
  'frost-flame-king-of-avalon': '킹 오브 아발론',
  'genshin-impact': '원신',
  'girls-frontline': '소녀전선',
  'goddess-of-genesis': '여신강림',
  'goddess-of-victory-nikke': '승리의 여신: 니케',
  'guardian-tales': '가디언 테일즈',
  'hay-day': '헤이데이',
  'honkai-impact-3rd': '붕괴3rd',
  'honkai-star-rail': '붕괴: 스타레일',
  'identity-v': '제5인격',
  'infinity-nikki': '인피니티 니키',
  'king-of-avalon': '킹 오브 아발론',
  'last-war-survival': '라스트워: 서바이벌',
  'legend-of-mushroom': '버섯커 키우기',
  'lineage-2m': '리니지2M',
  'lineage-w': '리니지W',
  'lord-of-heroes': '로드 오브 히어로즈',
  'love-nikki-dress-up-queen': '러브 니키',
  'lucky-defense-omfg': '운빨존많겜',
  'ludus-merge-battle-arena': '루두스',
  'lyssa-goddess-of-rage': '리사: 분노의 여신',
  'maplestory-idle-rpg': '메이플 키우기',
  'maplestory-m': '메이플스토리M',
  'mini-heroes-magic-throne': '미니히어로즈',
  'mobile-legends-bang-bang': '모바일 레전드',
  'monopoly-go': '모노폴리 고',
  'ni-no-kuni-cross-worlds': '두 번째 나라',
  'obsidian-knight': '옵시디언 나이트',
  'odin-valhalla-rising': '오딘: 발할라 라이징',
  'outerplane': '아우터플레인',
  'pokemon-go': '포켓몬 GO',
  'pokemon-unite': '포켓몬 유나이트',
  'pubg-mobile': '배틀그라운드 모바일',
  'punishing-gray-raven': '퍼니싱: 그레이 레이븐',
  'puzzles-survival': '퍼즐앤서바이벌',
  'ragnarok-m-classic': '라그나로크 M: 클래식',
  'ragnarok-origin': '라그나로크 오리진',
  'realms-of-pixel': '렐름 오브 픽셀',
  'rise-of-kingdoms': '라이즈 오브 킹덤즈',
  'seven-knights-re-birth': '세븐나이츠 리버스',
  'shining-nikki': '샤이닝 니키',
  'solitaire-grand-harvest': '솔리테어 그랜드 하베스트',
  'solo-leveling-arise': '나 혼자만 레벨업: 어라이즈',
  'space-shooter': '스페이스 슈터',
  'star-savior': '스타 세이비어',
  'starseed-asnia-trigger': '스타시드: 아스니아 트리거',
  'state-of-survival': '스테이트 오브 서바이벌',
  'street-fighter-duel': '스트리트 파이터 듀얼',
  'summoners-war-lost-centuria': '서머너즈 워: 백년전쟁',
  'summoners-war-sky-arena': '서머너즈 워',
  'tiles-survive': '타일즈 서바이브',
  'top-war-battle-game': '탑워: 배틀게임',
  'tower-of-fantasy': '타워 오브 판타지',
  'viking-rise': '바이킹 라이즈',
  'watcher-of-realms': '와쳐 오브 렐름',
  'whiteout-survival': '화이트아웃 서바이벌',
  'wittle-defender': '위틀 디펜더',
  'wuthering-waves': '명조: 워더링 웨이브',
  'x-clash': 'X 클래시',
  'zenless-zone-zero': '젠레스 존 제로',
};
